spring:
  application:
    name: uDiscovery
server:
  port: ${UDISCOVERY_PORT:8761}
eureka:
  instance:
      hostname: ${EUREKA_SERVER_HOSTNAME:peer1}
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

    