server:
  port: ${APP_PORT:8080}
eureka:
  client:
    enabled: ${EUREKA_CLIENT_ENABLED:false}
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
spring:
  application:
    name: uGateway
  cloud:
    gateway:
      routes:
      - id: uShort-back
        uri: ${USHORT_BACK_ADDRESS:lb://ushort}
        predicates:
        - Path=/v1/ushort/**
        
logging:
  level:
    org.springframework.cloud.gateway: TRACE 