server:
  port: ${APP_PORT:8080}
eureka:
  client:
    enabled: ${EUREKA_CLIENT_ENABLED:true}
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
spring:
  application:
    name: uGateway
  cloud:
    gateway:
      default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
              allowedOrigins: ${GATEWAY_CORS_ORIGINS:*}
              allowedHeaders: ${GATEWAY_CORS_HEADERS:*}
              allowedMethods: ${GATEWAY_CORS_METHODS:*} 
      routes:
      - id: ushort
        uri: ${USHORT_BACK_ADDRESS:lb://ushort}
        predicates:
        - Path=/v1/ushort/**