services:
  cassandra:
    image: cassandra:jammy
    container_name: cassandra
    ports:
      - "9042:9042" # Porta padrão do Cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=my_cluster
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_DC=daviCenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_AUTHENTICATOR=PasswordAuthenticator
      - CASSANDRA_AUTHORIZER=CassandraAuthorizer
      - CASSANDRA_ROLE_MANAGER=CassandraRoleManager
      - CASSANDRA_SUPERUSER_NAME=cassandra
      - CASSANDRA_SUPERUSER_PASSWORD=cassandra
    volumes:
      - /var/lib/cassandra:/var/lib/cassandra
    networks:
      - shared_network
networks:
  shared_network:
    external: true
