services:
  eureka-server:
    build: .
    container_name: gateway-server
    ports:
      - "8080:8080" 
    networks:
      - shared_network
    environment:
      APP_PORT: 8080
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/

networks:
  shared_network:
    external: true
